vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "'a", "'azz")
vim.keymap.set("n", "'q", "'qzz")
vim.keymap.set("v", "<leader>{", "c{<Esc>pa}")
vim.keymap.set("v", "<leader>[", "c[<Esc>pa]")
vim.keymap.set("v", "<leader>(", "c(<Esc>pa)")
vim.keymap.set("v", "<leader>'", "c'<Esc>pa'")
vim.keymap.set("v", '<leader>"', 'c"<Esc>pa"')
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("v", "<leader>p", "\"_dP")
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set("n", "<leader>w", "<C-w>")
vim.keymap.set("i", "zz", "<Esc>zza")
vim.keymap.set("n", "<leader><Up>", ":resize -2<CR>")
vim.keymap.set("n", "<leader><Down>", ":resize +2<CR>")
vim.keymap.set("n", "<leader><Left>", ":vertical resize -2<CR>")
vim.keymap.set("n", "<leader><Right>", ":vertical resize +2<CR>")
vim.keymap.set("t", "<leader><Up>", "<cmd>resize -2<CR>")
vim.keymap.set("t", "<leader><Down>", "<cmd>resize +2<CR>")
vim.keymap.set("t", "<leader><Left>", "<cmd>vertical resize -2<CR>")
vim.keymap.set("t", "<leader><Right>", "<cmd>vertical resize +2<CR>")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("t", "<Esc>", '<C-\\><C-n>')
